import { SignInButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'
import { CreatePostWizard } from '~/components/CreatePostWizard'
import { PostView } from '~/components/PostView'

import { api } from '~/utils/api'

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery()
  const user = useUser()

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data].map((props) => (
              <PostView key={props.post.id} {...props} />
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
